repos:
- repo: local
  hooks:
    - id: check-gpt4
      name: Prevent GPT-4 usage
      entry: python scripts/check_gpt_usage.py
      language: system
      types: [python]
      stages: [pre-commit]

    - id: check-affiliate-links
      name: Validate Affiliate Links
      entry: python scripts/check_affiliate_links.py
      language: system
      types: [python]
      stages: [pre-commit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
